version: "3.7"
services:
  jenkins:
    image: registry.colpatria.com/base/jenkins:lts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./jenkins_home:/var/jenkins_home"
    ports:
      - 8080:8080